export const REQUEST_RACES_BY_SEASON_PENDING = 'REQUEST_RACES_BY_SEASON_PENDING'
export const REQUEST_RACES_BY_SEASON_SUCCESS = 'REQUEST_RACES_BY_SEASON_SUCCESS'
export const REQUEST_RACES_BY_SEASON_FAILED = 'REQUEST_RACES_BY_SEASON_FAILED'

export const REQUEST_LAST_RACE_PENDING = 'REQUEST_LAST_RACE_PENDING'
export const REQUEST_LAST_RACE_SUCCESS = 'REQUEST_LAST_RACE_SUCCESS'
export const REQUEST_LAST_RACE_FAILED = 'REQUEST_LAST_RACE_FAILED'
