export const REQUEST_STANDINGS_PENDING = 'REQUEST_STANDINGS_PENDING'
export const REQUEST_STANDINGS_SUCCESS = 'REQUEST_STANDINGS_SUCCESS'
export const REQUEST_STANDINGS_FAILED = 'REQUEST_STANDINGS_FAILED'
